[package]
name = "whisper_cpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whisper_cpp_sys = { version = "^0.1.0", path = "../whisper_cpp_sys" }
