name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest, macos-latest-xl ]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM (for llvm-copy)
      if: target.os == 'macos'
      run: |
        brew update
        brew install llvm@17
        echo "$(brew --prefix llvm@17)/bin" >> $GITHUB_PATH
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: mkdir /tmp/models && cargo test --verbose
      env:
        WHISPER_TEST_MODELS: "/tmp/models"
