name: Rust build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-20.04
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM (for llvm-copy)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install llvm@17
        echo "$(brew --prefix llvm@17)/bin" >> $GITHUB_PATH
    - name: Update submodules
      run: git submodule update --init --recursive
    - if: matrix.target
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: mkdir /tmp/models && cargo test --verbose
      env:
        WHISPER_TEST_MODELS: "/tmp/models"
